# Generated by Django 4.0.3 on 2022-03-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0002_reservation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'room_id')},
        ),
    ]
